version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: synergium-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: synergium
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: synergium-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: