services:
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    env_file:
      - ../.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
